services:
  web:
    build:
      context: ./php
    container_name: cinema_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    command: ["apache2-foreground"]

  db:
    image: mysql:5.7
    container_name: cinema_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: cinema_pass
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cinema_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: cinema_user
      PMA_PASSWORD: cinema_pass
      PMA_ARBITRARY: 1
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: cinema_frontend
    volumes:
      - ./frontend/frontend-app:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    command: >
      sh -c "npm install && ng serve --host 0.0.0.0 --poll 1000 --disable-host-check"
    depends_on:
      - web

volumes:
  db_data: