# config/services.yaml

parameters:
# Global parameters can go here

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true

    # Factories
    App\Factory\:
        resource: '../src/Factory/*'

    # Services
    App\Service\:
        resource: '../src/Service/*'

     #repos
    App\Repository\:
        resource: '../src/Repository'
        tags: [ 'doctrine.repository_service' ]
        autowire: true


    # Bind interfaces to concrete services
    App\Service\AuthServiceInterface: '@App\Service\AuthService'
    App\Service\BookingServiceInterface: '@App\Service\BookingService'
    App\Service\CinemaServiceInterface: '@App\Service\CinemaService'
    App\Service\FilmServiceInterface: '@App\Service\FilmService'
    App\Service\UserServiceInterface: '@App\Service\UserService'
    App\Service\TheaterServiceInterface: '@App\Service\TheaterService'
    # Explicit alias for your FactoryServiceProviderInterface
    App\Services\FactoryServiceProviderInterface:
        alias: App\Services\FactoryServiceProvider
    # Explicit interface to implementation mapping
    App\Service\Interfaces\AuthServiceInterface:
        alias: App\Service\AuthService
