# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

        # Controllers are public
        App\Controller\:
            resource: '../src/Controller'
            public: true

    # Factories
    App\Factory\:
        resource: '../src/Factory/*'

    # Services
    App\Service\:
        resource: '../src/Service/*'


    # Bind interfaces to concrete implementations
    App\Services\FactoryServiceProviderInterface: '@App\Services\FactoryServiceProvider'
    # Bind interfaces to concrete implementations explicitly if needed
    App\Services\UserServiceInterface: '@App\Services\UserService'
    App\Services\HomeServiceInterface: '@App\Services\HomeService'
    App\Services\BookingServiceInterface: '@App\Services\BookingService'



