# config/services.yaml

parameters:
# You can define global parameters here if needed
# e.g. app.default_timezone: 'Africa/Johannesburg'

services:
    # default configuration for services in this file
    _defaults:
        autowire: true      # Automatically inject dependencies
        autoconfigure: true # Automatically apply Symfony tags
        public: false       # Services are private by default

    # Controllers
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true        # Controllers must be public for routing

    # Factories
    App\Factory\:
        resource: '../src/Factory/*'

    # Services
    App\Service\:
        resource: '../src/Service/*'

    # Explicit alias for your FactoryServiceProviderInterface
    App\Services\FactoryServiceProviderInterface:
        alias: App\Services\FactoryServiceProvider
