security:
    encoders:
        App\Entity\CbUsers:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\CbUsers
                property: email

    firewalls:
        login:
            pattern:  ^/api/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/bookings, roles: ROLE_USER }
#straight from the docs